enable-magisk-update = true
parallel-jobs = 1
compression-level = 9

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "yt-rvx"
patches-source = "anddea/revanced-patches"
cli-source = "ReVanced/revanced-cli"

# Revanced patches
[YouTube]
enabled = false
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
rv-brand = "Revanced"

[YT-Music]
enabled = false
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
rv-brand = "Revanced"

# inotia00 patches
[YT-Music-Extended]
enabled = false
arch = "arm64-v8a"
build-mode = "module"
app-name = "YouTube-Music"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Dark theme'"
included-patches = ""
patcher-args = " -e 'GmsCore support' -OpackageNameYouTubeMusic='com.rvx.android.youtube.music'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
module-prop-name = "ytm-rvx"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"

[YouTube-Extended]
enabled = false
build-mode = "module"
arch = "arm64-v8a"
app-name = "YouTube"
excluded-patches = "'Custom branding icon for YouTube' 'Translations for YouTube' 'Custom branding name for YouTube' 'Theme' 'MaterialYou' 'Enable gradient loading screen' 'Force hide player buttons background'"
included-patches = "'Visual preferences icons'"
patcher-args = " -e 'GmsCore support' -OpackageNameYouTube='com.rvx.android.youtube'"
version = "auto"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "yt-rvx"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"

# anddea patches
[YT-Music-Extended-Anddea]
arch = "arm64-v8a"
build-mode = "module"
app-name = "YouTube-Music"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Dark theme'"
included-patches = ""
patcher-args = " -e 'GmsCore support' -OpackageNameYouTubeMusic='com.rvxanddea.android.youtube.music'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
module-prop-name = "ytm-rvx-anddea"
patches-source = "anddea/revanced-patches"
cli-source = "ReVanced/revanced-cli"
rv-brand = "RVX Anddea"

[YouTube-Extended-Anddea]
build-mode = "module"
arch = "arm64-v8a"
app-name = "YouTube"
excluded-patches = "'Custom branding icon for YouTube' 'Translations for YouTube' 'Custom branding name for YouTube' 'Theme' 'MaterialYou' 'Enable gradient loading screen' 'Force hide player buttons background'"
included-patches = "'Visual preferences icons'"
patcher-args = " -e 'GmsCore support' -OpackageNameYouTube='com.rvxanddea.android.youtube'"
version = "auto"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "yt-rvx-anddea"
patches-source = "anddea/revanced-patches"
cli-source = "ReVanced/revanced-cli"
rv-brand = "RVX Anddea"

# Morphe patches
[YT-Music-Morphe]
arch = "arm64-v8a"
build-mode = "module"
app-name = "YouTube-Music"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Dark theme'"
included-patches = ""
patcher-args = " -e 'GmsCore support' -OpackageNameYouTubeMusic='com.morphe.android.youtube.music'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
module-prop-name = "ytm-morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe" 

[YouTube-Morphe]
build-mode = "module"
arch = "arm64-v8a"
app-name = "YouTube"
excluded-patches = "'Custom branding icon for YouTube' 'Translations for YouTube' 'Custom branding name for YouTube' 'Theme' 'MaterialYou' 'Enable gradient loading screen' 'Force hide player buttons background'"
included-patches = "'Visual preferences icons'"
patcher-args = " -e 'GmsCore support' -OpackageNameYouTube='com.morphe.android.youtube'"
version = "auto"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "yt-morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"

[Music-Morphe]
enabled = false
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
app-name = "Reddit"
rv-brand = "Morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[GooglePhotos]
enabled = false
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[Twitter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "apk"
dpi = "120-640dpi"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[TikTok]
enabled = false
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"